version: "2.1"
services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin@sha256:d94b82bb7f6d794fb8d281a373a63ed0e64996224a1ba09f3bbfb14700345943
    container_name: jellyfin
    env_file:
      - .env-files/linuxserverio.env
    volumes:
      - ./volumes/config:/config
      - ${MEDIA_VOLUME}/movies:/data/movies
      - ${MEDIA_VOLUME}/shows:/data/shows
    restart: unless-stopped

networks:
  default:
    name: ${SWAG_NETWORK}
    external: true

