version: "2.1"
services:
  qbittorrent-gluetun-internal:
    image: lscr.io/linuxserver/qbittorrent@sha256:cd564c2074c3f502f5cd17df107aa7d1b7131fc5942c94f8c5ee284c628d5f58
    container_name: qbittorrent-gluetun-internal
    network_mode: service:qbittorrent-gluetun
    env_file:
      - .linuxserverio.env
    volumes:
      - ./volumes/config:/config
      - ${MEDIA_VOLUME}/downloads:/downloads
    depends_on:
      - qbittorrent-gluetun
    restart: unless-stopped

  qbittorrent-gluetun:
    image: qmcgaw/gluetun@sha256:7b9fbfc187e7603d0039bf777ea4b278409e42f6d038c02deb14727153591ac5
    container_name: qbittorrent-gluetun
    cap_add:
      - NET_ADMIN
    env_file:
      - .gluetun.env
    environment:
      # Allow access to host local network
      - FIREWALL_OUTBOUND_SUBNETS=${HOST_NETWORK_SUBNET}
      # Expose health service externally
      - HEALTH_SERVER_ADDRESS=0.0.0.0:9999
    volumes:
      - ./volumes/gluetun:/gluetun
    restart: unless-stopped

networks:
  default:
    name: ${SWAG_NETWORK}
    external: true

