version: "2.1"
services:

  wireguard-gluetun-internal:
    image: lscr.io/linuxserver/wireguard@sha256:a27dc2b63245fa1c20fc55edf9aebf7cf3add71000557177c9fa62dba65b5d29
    container_name: wireguard-gluetun-internal
    network_mode: service:wireguard-gluetun
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    env_file:
      - wireguard.env
      - linuxserverio.env
    environment:
      - SERVERURL=${DUCKDNS_SUBDOMAIN}.duckdns.org
      - SERVERPORT=${WIREGUARD_GLUETUN_SERVERPORT}
      - INTERNAL_SUBNET=${WIREGUARD_NETWORK_SUBNET}
      # Tunnel everything through vpn
      - ALLOWEDIPS=0.0.0.0/1,128.0.0.0/1
    volumes:
      - ./volumes/config:/config
    restart: unless-stopped

  # We use dnsmasq instead of wireguard's built-in coredns
  # By hosting DNS server in the same gluetun container we tunnel queries through VPN
  wireguard-gluetun-internal-dnsmasq:
    image: strm/dnsmasq
    container_name: wireguard-gluetun-internal-dnsmasq
    network_mode: service:wireguard-gluetun-internal
    cap_add:
      - NET_ADMIN
    volumes:
      - ./volumes/dnsmasq.conf:/etc/dnsmasq.conf
    restart: unless-stopped

  wireguard-gluetun:
    image: qmcgaw/gluetun@sha256:7b9fbfc187e7603d0039bf777ea4b278409e42f6d038c02deb14727153591ac5
    container_name: wireguard-gluetun
    cap_add:
      - NET_ADMIN
    env_file:
      - gluetun.env
    environment:
      # No DNS over TLS as that would clash with dnsmasq
      - DOT=off
      # Allow access to host local network
      - FIREWALL_OUTBOUND_SUBNETS=${HOST_NETWORK_SUBNET}
      # Expose health service externally
      - HEALTH_SERVER_ADDRESS=0.0.0.0:9999
    ports:
      - ${WIREGUARD_GLUETUN_SERVERPORT}:51820/udp
    volumes:
      - ./volumes/gluetun:/gluetun
    restart: unless-stopped

networks:
  default:
    name: ${MAIN_NETWORK}
    external: true

