version: "2.1"
services:
  swag:
    image: ghcr.io/linuxserver/swag@sha256:dfd88f7c39a9991a3ffb3f1d201db50b0013619c3e824a74219cda5151a2a8e8
    container_name: swag
    cap_add:
      - NET_ADMIN
    env_file:
      - linuxserverio.env
    environment:
      # Ref: https://docs.linuxserver.io/general/swag#create-container-via-duckdns-validation-with-a-wildcard-cert
      - URL=${DUCKDNS_SUBDOMAIN}.duckdns.org
      - SUBDOMAINS=wildcard
      - VALIDATION=duckdns
      - DUCKDNSTOKEN=${DUCKDNS_TOKEN}
    ports:
      - ${SWAG_HTTPS_PORT}:443
      # - ${SWAG_HTTP_PORT}:80
    volumes:
      - ./volumes/config:/config
    restart: on-failure

networks:
  default:
    name: ${REVERSE_PROXY_NETWORK}

