version: "2.1"
services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin@sha256:f100f33f0c104a38f070c12a8b9ba6d8484f234bce9a4be20268738be9a62045
    container_name: jellyfin
    env_file:
      - linuxserverio.env
    volumes:
      - ./volumes/config:/config
      - ${MEDIA_VOLUME}/movies:/data/movies
      - ${MEDIA_VOLUME}/shows:/data/shows
    restart: on-failure

networks:
  default:
    name: ${SWAG_NETWORK}
    external: true

