version: "2.1"
services:
  swag:
    image: ghcr.io/linuxserver/swag@sha256:dfd88f7c39a9991a3ffb3f1d201db50b0013619c3e824a74219cda5151a2a8e8
    container_name: swag
    cap_add:
      - NET_ADMIN
    env_file:
      - .env-files/linuxserverio.env
    environment:
      # Ref: https://docs.linuxserver.io/general/swag#create-container-via-duckdns-validation-with-a-wildcard-cert
      - URL=${DUCKDNS_SUBDOMAIN}.duckdns.org
      - SUBDOMAINS=wildcard
      - VALIDATION=duckdns
      - DUCKDNSTOKEN=${DUCKDNS_TOKEN}
    ports:
      - 443:443  # Using another port can lead to issues (e.g. header URL mismatch)
    networks:
      main-network:
        ipv4_address: ${MAIN_NETWORK_SWAG_ADDRESS}
      swag-network:
    volumes:
      - ./volumes/config:/config
    restart: unless-stopped

networks:
  main-network:
    name: ${MAIN_NETWORK}
    driver: bridge
    ipam:
      config:
        - subnet: ${MAIN_NETWORK_SUBNET}
          ip_range: ${MAIN_NETWORK_IP_RANGE}
  swag-network:
    name: ${SWAG_NETWORK}

