version: "3"
services:
  gluetun:
    image: qmcgaw/gluetun@sha256:7b9fbfc187e7603d0039bf777ea4b278409e42f6d038c02deb14727153591ac5
    container_name: ${GLUETUN_CONTAINER_NAME}
    cap_add:
      - NET_ADMIN
    env_file:
      - private.env
    volumes:
      - ./volumes/gluetun:/gluetun
    restart: on-failure

networks:
  default:
    name: ${REVERSE_PROXY_NETWORK}
    external: true

