version: "2.1"
services:

  wireguard:
    image: lscr.io/linuxserver/wireguard@sha256:a27dc2b63245fa1c20fc55edf9aebf7cf3add71000557177c9fa62dba65b5d29
    container_name: wireguard
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    env_file:
      - wireguard.env
      - linuxserverio.env
    environment:
      - SERVERPORT=${WIREGUARD_SERVERPORT}
      - INTERNAL_SUBNET=${WIREGUARD_NETWORK_SUBNET}
      # Tunnel everything through vpn
      - ALLOWEDIPS=0.0.0.0/1,128.0.0.0/1
    ports:
      - ${WIREGUARD_SERVERPORT}:51820/udp
    volumes:
      - ./volumes/config:/config
    restart: unless-stopped

  # We use dnsmasq instead of wireguard's built-in coredns
  wireguard-dnsmasq:
    image: strm/dnsmasq
    container_name: wireguard-dnsmasq
    network_mode: service:wireguard
    cap_add:
      - NET_ADMIN
    volumes:
      - ./volumes/dnsmasq.conf:/etc/dnsmasq.conf
    restart: unless-stopped

networks:
  default:
    name: ${MAIN_NETWORK}
    external: true

